---
driver:
  name: vagrant
provisioner:
  name: chef_solo
platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: ubuntu-16.04
- name: centos-6.8
- name: centos-7.2
- name: debian-6.0.10
- name: debian-7.11
- name: oraclelinux-5
  driver_config:
    box: oraclelinux-5
    box_url: http://cloud.terry.im/vagrant/oraclelinux-5-x86_64.box
- name: oraclelinux-6.5
  driver_config:
    box: oraclelinux-6
    box_url: http://cloud.terry.im/vagrant/oraclelinux-6-x86_64.box
- name: oraclelinux-7
  dfiver_config:
    box: oraclelinux-7
    box_url: http://cloud.terry.im/vagrant/oraclelinux-7-x86_64.box
verifier:
  name: inspec
suites:
- name: default
  run_list:
  - recipe[os-hardening::default]
  verifier:
    inspec_tests:
    - https://github.com/dev-sec/tests-os-hardening
- name: modules_disabled
  run_list:
  - recipe[os-hardening::default]
  attributes:
    os-hardening:
      security:
        kernel:
          enable_module_loading: false
  verifier:
    inspec_tests:
    - https://github.com/dev-sec/tests-os-hardening
