AllCops:
  Excludes:
    - vendor/**
    - metadata.rb
    - test/integration/**
    - shared_test_repo/**

Documentation:
  Enabled: false
AlignParameters:
  Enabled: true
Encoding:
  Enabled: true
HashSyntax:
  Enabled: true
LineLength:
  Enabled: false
MethodLength:
  Max: 30
NumericLiterals:
  MinDigits: 10
